routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profil', 'HomeController@profilUser')->name('profil_user');
Route::get('/edit_picture_user', 'HomeController@editPictureUser')->name('edit_picture_user');
Route::post('/upload-img', 'HomeController@uploadImg')->name('upload-img');
Route::get('/offre/{offre}', 'HomeController@viewOffre')->name('view_offre');
Route::get('/postuler/{offre}', 'HomeController@postuler')->name('postuler');
Route::get('/resilier_candidature/{candidature}', 'HomeController@resilierCandidature')->name('resilier_candaidature');

Route::prefix('admin')->group(function(){
	Route::name('admin.')->group(function () {
		Route::get('/', 'Auth\AdminLoginController@showLoginForm');
		Route::post('/', 'Auth\AdminLoginController@login')->name('login');
		Route::get('/welcome', 'AdminController@index')->name('index');
		Route::get('/offre', 'AdminController@showFormOffre')->name('show_form_offre');
		Route::post('/offre', 'AdminController@createOffre')->name('create_offre');
		Route::get('/offre/edit/{offre}', 'AdminController@editOffre')->name('edit_offre');
		Route::get('/offre/destroy/{offre}', 'AdminController@destroyOffre')->name('destroy_offre');
		Route::get('/offre/{offre}', 'AdminController@showOffre')->name('show_offre');

		Route::get('/accept_candidature/{candidature}', 'AdminController@acceptCandidature')->name('accept_candidature');

		Route::get('/profil/{user}', 'AdminController@profilUser')->name('profil_user');
Route::get('/resilier_candidature/{candidature}', 'AdminController@resilierCandidature')->name('resilier_candidature');



			


	});

		});

resources/views/admin/form_offre.blade.php
@extends('layouts.master')
@push('stylesheets')
<link rel="stylesheet" type="text/css" href="{{ asset('summernote/dist/summernote-bs4.css') }}">
@endpush
@section('content')
<div class="row d-flex justify-content-center">
    <div class="col-md-10">
    	<div class="card">
    		<div class="card-header bg-danger text-white">Offre</div>
    		<div class="card-body">
    			@if ($errors->any())
		        <div class="alert alert-danger">
		          <ul class="list-unstyled">
		            @foreach ($errors->all() as $error)
		              <li>{!! $error !!}</li>
		            @endforeach
		          </ul>
		        </div>
		      @endif
    			<form action="{{ route('admin.create_offre') }}" method="POST">
    				@csrf
    				<input type="text" name="idoffres" value="{{ old('idoffres',optional($offre)->idoffres) }}" hidden="">
				  <div class="form-group">
				    <label for="titre">Titre</label>
				    <input type="text" name="titre" class="form-control" id="titre" required="" value="{{ old('titre',optional($offre)->titre) }}">
				  </div>
				  <div class="form-group">
				    <label for="resume">Resumé</label>
				    <input type="text" name="resume" class="form-control" id="resume" maxlength="255" required="" value="{{ old('resume',optional($offre)->resume) }}">
				  </div>
				  <div class="form-group">
				    <label for="idtypes_offres">Type de l'offre</label>
				    <select  class="form-control" id="idtypes_offres" name="idtypes_offres" >
				    @foreach(App\Models\Types_offre::get() as $tp)
				      <option value="{{ $tp->idtypes_offres }}">{{ $tp->lib }}</option>
				    @endforeach
				      
				    </select>
				  </div>
				  <div class="form-group">
				    <label for="description">Détail</label>
				    <textarea class="form-control" name="description" id="description" rows="10" >{!! old('description',optional($offre)->description) !!}</textarea>
				  </div>
				  <button type="submit" class="btn btn-primary mb-2 btn-block">Valider</button>
				</form>
    		</div>
    	</div>
    </div>
        
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript" src="{{ asset('summernote/dist/summernote-bs4.js') }}"></script>
<script type="text/javascript">
	$(document).ready(function() {
  	$('#description').summernote({
  		height: 300,
  	});
});
</script>
@endpush

resources/views/admin/index.blade.php
@extends('layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container"  >
	<div class="row">
        <div class="col-md-12">
        	<a href="{{ route('admin.create_offre') }}" class="btn btn-info "><span class="fa fa-plus-circle"> </span> Nouvelle offre</a>
         {{-- <h2 class="badge badge-pill badge-info">Liste des offres</h2>    --}}
        </div>
    </div>
    
     {{-- <hr /> --}}
	<div class="card bg-light mb-3">
	  <div class="card-body" >
		{!!$dataTable->table() !!}
	  </div>
	</div>
</div>	
@stop
@push('scripts')
{!!$dataTable->scripts() !!}
@endpush

resources/views/admin/view_offre.blade.php
@extends('layouts.master')
@section('content')

<div class="row">
    <div class="col-md-8">
      <div class="card bg-light col-12 ">
        <div class="card-header bg-danger">
            <h5 class="card-title text-white">{{ $offre->titre }}</h5>
        </div>
        <div class="card-body ">
            <div class="">
              <h1 class="display-6">{{ $offre->titre }}</h1>
              <p class="lead">{{ $offre->resume }}</p>
              <hr class="my-4">
              <p>{!! $offre->description !!}</p>
                {{-- <a href="{{ route('postuler',$offre->idoffres) }}" class="btn btn-primary btn-lg">Postuler</a> --}}
              
            </div>
        </div>
      </div>
    </div>
    {{-- <div class="col-md-1"></div> --}}
    <div class="col-md-4">
        <div class="row">
            <div class="card bg-light col-12 " style="max-height: 300px">
                <div class="card-header bg-danger">
                    <h5 class="card-title text-white">Candidatures</h5>
                </div>
                <div class="card-body scroll-panel">
                  @if($candidats->isNotEmpty())
                  @foreach($candidats as $c)
                  <div class="card">
                    <div class="card-body">
                      <div class="row">
                        <div class="col-5">
                          <img src="{{ img_profil($c->idusers) }}" class="img-fluid rounded-circle" alt="Bil" width="90 " height="90">
                        </div>
                        <div class="col-7">
                          <h5>{{ $c->prenom .' '.$c->nom }} </h5>
                          
                          <a href="{{ route('admin.profil_user',$c->idusers) }}" class="btn bg-info text-white"><span class="fa fa-eye"></span></a>
                          <a href="{{ route('admin.accept_candidature',$c->idcandidatures) }}" class="btn bg-success text-white"><span class="fa fa-check"></span></a>
                          <a href="{{ route('admin.resilier_candidature',$c->idcandidatures) }}" class="btn bg-danger text-white"><span class="fa fa-trash"></span></a>
                        </div>
                      </div>
                    </div>
                  </div>
                  @endforeach
                  @endif
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="card bg-light col-12 " style="max-height: 300px">
                <div class="card-header bg-danger">
                    <h5 class="card-title  text-white">Bénéficiaires</h5>
                </div>
                <div class="card-body scroll-panel">
                  @if($beneficiaires->isNotEmpty())
                  @foreach($beneficiaires as $c)
                  <div class="card">
                    <div class="card-body">
                      <div class="row">
                        <div class="col-5">
                          <img src="{{ img_profil($c->idusers) }}" class="img-fluid rounded-circle" alt="Bil" width="90 " height="90">
                        </div>
                        <div class="col-7">
                          <h5>{{ $c->prenom .' '.$c->nom }} </h5>
                          
                          <a href="{{ route('admin.profil_user',$c->idusers) }}" class="btn bg-info text-white"><span class="fa fa-eye"></span></a>
                          {{-- <a href="" class="btn bg-success text-white"><span class="fa fa-check"></span></a> --}}
                          {{-- <a href="" class="btn bg-danger text-white"><span class="fa fa-trash"></span></a> --}}
                        </div>
                      </div>
                    </div>
                  </div>
                  @endforeach
                  @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection